# Generated by Django 3.0.5 on 2020-04-24 08:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20200424_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='createdAt',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At'),
        ),
    ]
