# Generated by Django 3.0.5 on 2020-04-24 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20200424_1523'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Address',
            new_name='PersonAddress',
        ),
    ]
