# Generated by Django 3.0.5 on 2020-04-27 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20200427_1250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personeducation',
            old_name='the_city',
            new_name='building_city',
        ),
        migrations.RenameField(
            model_name='personeducation',
            old_name='the_name',
            new_name='building_name',
        ),
        migrations.RenameField(
            model_name='personeducation',
            old_name='the_number',
            new_name='building_number',
        ),
        migrations.AlterField(
            model_name='personeducation',
            name='building_type',
            field=models.CharField(max_length=30, verbose_name='Тип заведения'),
        ),
    ]
