# Generated by Django 3.0.5 on 2020-04-27 14:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_auto_20200427_1310'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personfamilyties',
            old_name='date_birthday',
            new_name='family_tie_date_birthday',
        ),
        migrations.RenameField(
            model_name='personfamilyties',
            old_name='first_name',
            new_name='family_tie_first_name',
        ),
        migrations.RenameField(
            model_name='personfamilyties',
            old_name='job',
            new_name='family_tie_job',
        ),
        migrations.RenameField(
            model_name='personfamilyties',
            old_name='last_name',
            new_name='family_tie_last_name',
        ),
        migrations.RenameField(
            model_name='personfamilyties',
            old_name='link_social_net',
            new_name='family_tie_link_social_net',
        ),
        migrations.RenameField(
            model_name='personfamilyties',
            old_name='middle_name',
            new_name='family_tie_middle_name',
        ),
        migrations.RenameField(
            model_name='personfamilyties',
            old_name='relation',
            new_name='family_tie_relation',
        ),
        migrations.RemoveField(
            model_name='personfamilyties',
            name='working_position',
        ),
        migrations.AddField(
            model_name='personfamilyties',
            name='family_tie_working_position',
            field=models.CharField(default=django.utils.timezone.now, max_length=30, verbose_name='Должность'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='personsocialnet',
            name='name_social_net',
            field=models.CharField(max_length=30, verbose_name='Название соц. сети'),
        ),
    ]
