# Generated by Django 3.0.5 on 2020-05-24 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_auto_20200427_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='рreviouslastname',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
    ]
