# Generated by Django 3.0.5 on 2020-05-28 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0017_auto_20200528_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personfamilyties',
            name='family_tie_date_birthday',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
    ]
