# Generated by Django 3.0.5 on 2020-05-29 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0019_auto_20200528_1529'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Название компании')),
                ('company_inn', models.CharField(blank=True, max_length=30, null=True, verbose_name='ИНН компании')),
                ('company_is_active', models.CharField(blank=True, max_length=30, null=True, verbose_name='Действует?')),
                ('company_date_period_from', models.DateField(blank=True, null=True, verbose_name='Период работы с')),
                ('company_date_period_to', models.DateField(blank=True, null=True, verbose_name='Период работы по')),
            ],
        ),
        migrations.AlterField(
            model_name='personfamilyties',
            name='family_tie_link_social_net',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на соцсеть'),
        ),
        migrations.AlterField(
            model_name='personsocialnet',
            name='link_social_net',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на соцсеть'),
        ),
        migrations.CreateModel(
            name='PersonWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('work_position', models.CharField(blank=True, max_length=30, null=True, verbose_name='Должность')),
                ('work_date_period_from', models.DateField(blank=True, null=True, verbose_name='Период работы с')),
                ('work_date_period_to', models.DateField(blank=True, null=True, verbose_name='Период работы по')),
                ('company', models.ManyToManyField(to='web.Company')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Person')),
            ],
        ),
        migrations.CreateModel(
            name='PersonSocialRelationsVK',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('social_relations_vk_link_account', models.URLField(blank=True, null=True, verbose_name='Ссылка на аккаунт в соц.сети')),
                ('social_relations_vk_first_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Имя')),
                ('social_relations_vk_last_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Фамилия')),
                ('social_relations_vk_middle_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Отчество')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Person')),
            ],
        ),
        migrations.CreateModel(
            name='PersonSocialRelationsInst',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('social_relations_inst_link_account', models.URLField(blank=True, null=True, verbose_name='Ссылка на аккаунт в соц.сети')),
                ('social_relations_inst_first_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Имя')),
                ('social_relations_inst_last_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Фамилия')),
                ('social_relations_inst_middle_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Отчество')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Person')),
            ],
        ),
        migrations.CreateModel(
            name='PersonSocialRelationsGroupVK',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('social_relations_vk_link_group', models.URLField(blank=True, null=True, verbose_name='Ссылка на группы')),
                ('social_relations_vk_name_group', models.CharField(blank=True, max_length=150, null=True, verbose_name='Имя')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Person')),
            ],
        ),
        migrations.CreateModel(
            name='PersonSocialRelationsGroupInst',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('social_relations_inst_link_group', models.URLField(blank=True, null=True, verbose_name='Ссылка на группы')),
                ('social_relations_inst_name_group', models.CharField(blank=True, max_length=150, null=True, verbose_name='Имя')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Person')),
            ],
        ),
        migrations.CreateModel(
            name='PersonSocialRelationsGroupFB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('social_relations_fb_link_group', models.URLField(blank=True, null=True, verbose_name='Ссылка на группы')),
                ('social_relations_fb_name_group', models.CharField(blank=True, max_length=150, null=True, verbose_name='Имя')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Person')),
            ],
        ),
        migrations.CreateModel(
            name='PersonSocialRelationsGroupCM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('social_relations_cm_link_group', models.URLField(blank=True, null=True, verbose_name='Ссылка на группы')),
                ('social_relations_cm_name_group', models.CharField(blank=True, max_length=150, null=True, verbose_name='Имя')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Person')),
            ],
        ),
        migrations.CreateModel(
            name='PersonSocialRelationsFB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('social_relations_fb_link_account', models.URLField(blank=True, null=True, verbose_name='Ссылка на аккаунт в соц.сети')),
                ('social_relations_fb_first_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Имя')),
                ('social_relations_fb_last_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Фамилия')),
                ('social_relations_fb_middle_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Отчество')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Person')),
            ],
        ),
        migrations.CreateModel(
            name='PersonSocialRelationsCM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('social_relations_cm_link_account', models.URLField(blank=True, null=True, verbose_name='Ссылка на аккаунт в соц.сети')),
                ('social_relations_cm_first_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Имя')),
                ('social_relations_cm_last_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Фамилия')),
                ('social_relations_cm_middle_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Отчество')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Person')),
            ],
        ),
        migrations.CreateModel(
            name='PersonIP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('ip_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Название ИП')),
                ('ip_inn', models.CharField(blank=True, max_length=30, null=True, verbose_name='ИНН')),
                ('ip_is_active', models.CharField(blank=True, max_length=30, null=True, verbose_name='Действует?')),
                ('ip_date_period_from', models.DateField(blank=True, null=True, verbose_name='Период работы с')),
                ('ip_date_period_to', models.DateField(blank=True, null=True, verbose_name='Период работы по')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Person')),
            ],
        ),
        migrations.CreateModel(
            name='PersonCompaniesFounder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('companies_founder', models.CharField(blank=True, max_length=30, null=True, verbose_name='Сейчас является учредителем?')),
                ('companies_founder_date_period_from', models.DateField(blank=True, null=True, verbose_name='являлся учредителем с')),
                ('companies_founder_date_period_to', models.DateField(blank=True, null=True, verbose_name='являлся учредителем по')),
                ('company', models.ManyToManyField(to='web.Company')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Person')),
            ],
        ),
        migrations.CreateModel(
            name='PersonCompaniesCEO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('companies_ceo', models.CharField(blank=True, max_length=30, null=True, verbose_name='Сейчас является ген.дир?')),
                ('companies_ceo_date_period_from', models.DateField(blank=True, null=True, verbose_name='Ген. дир с')),
                ('companies_ceo_date_period_to', models.DateField(blank=True, null=True, verbose_name='Ген. дир по')),
                ('company', models.ManyToManyField(to='web.Company')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Person')),
            ],
        ),
        migrations.CreateModel(
            name='IPDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('ip_detail_okved', models.CharField(blank=True, max_length=50, null=True, verbose_name='Основной ОКВЕД')),
                ('ip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.PersonIP')),
            ],
        ),
        migrations.CreateModel(
            name='FellowTraveler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('fellow_traveler_first_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Имя')),
                ('fellow_traveler_last_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Фамилия')),
                ('fellow_traveler_middle_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Отчество')),
                ('fellow_traveler_date_birthday', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('fellow_traveler_city_from', models.CharField(blank=True, max_length=50, null=True, verbose_name='Город отправления')),
                ('fellow_traveler_city_to', models.CharField(blank=True, max_length=50, null=True, verbose_name='Город прибытия')),
                ('fellow_traveler_date_trip', models.DateField(blank=True, null=True, verbose_name='Дата поездки')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Person')),
            ],
        ),
    ]
