# Generated by Django 3.0.5 on 2020-05-29 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0020_auto_20200529_1810'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FellowTraveler',
            new_name='PersonFellowTraveler',
        ),
    ]
