# Generated by Django 3.0.5 on 2020-05-30 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0021_auto_20200529_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='person_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='person',
            name='person_negative',
            field=models.TextField(blank=True, null=True, verbose_name='Негатив'),
        ),
        migrations.AlterField(
            model_name='person',
            name='date_birthday',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='person',
            name='middle_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='person',
            name='person_characteristic',
            field=models.TextField(blank=True, null=True, verbose_name='Характеристика'),
        ),
        migrations.AlterField(
            model_name='personcompaniesceo',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.Person'),
        ),
        migrations.AlterField(
            model_name='personcompaniesfounder',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.Person'),
        ),
    ]
