# Generated by Django 3.0.5 on 2020-05-31 15:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0022_auto_20200530_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=30, verbose_name='Имя'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=30, verbose_name='Фамилия'),
            preserve_default=False,
        ),
    ]
