# Generated by Django 3.0.5 on 2020-06-06 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0023_auto_20200531_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='inn',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_is_active',
            field=models.BooleanField(blank=True, null=True, verbose_name='Действует?'),
        ),
        migrations.AlterField(
            model_name='personip',
            name='ip_is_active',
            field=models.BooleanField(blank=True, null=True, verbose_name='Действует?'),
        ),
        migrations.CreateModel(
            name='PersonWorkWOC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('company_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Название компании')),
                ('company_inn', models.CharField(blank=True, max_length=30, null=True, verbose_name='ИНН компании')),
                ('work_position', models.CharField(blank=True, max_length=30, null=True, verbose_name='Должность')),
                ('work_date_period_from', models.DateField(blank=True, null=True, verbose_name='Период работы в комании с')),
                ('work_date_period_to', models.DateField(blank=True, null=True, verbose_name='Период работы в компании по')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Person')),
            ],
        ),
        migrations.CreateModel(
            name='PersonCompaniesFounderWOC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('company_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Название компании')),
                ('company_inn', models.CharField(blank=True, max_length=30, null=True, verbose_name='ИНН компании')),
                ('company_share', models.IntegerField(blank=True, null=True, verbose_name='Доля в компании')),
                ('company_date_period_from', models.DateField(blank=True, null=True, verbose_name='Период работы компании с')),
                ('company_date_period_to', models.DateField(blank=True, null=True, verbose_name='Период работы компании по')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.Person')),
            ],
        ),
        migrations.CreateModel(
            name='PersonCompaniesCEOWOC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('company_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Название компании')),
                ('company_inn', models.CharField(blank=True, max_length=30, null=True, verbose_name='ИНН компании')),
                ('companies_ceo_date_period_from', models.DateField(blank=True, null=True, verbose_name='Ген. дир с')),
                ('companies_ceo_date_period_to', models.DateField(blank=True, null=True, verbose_name='Ген. дир по')),
                ('company_date_period_from', models.DateField(blank=True, null=True, verbose_name='Период работы компании с')),
                ('company_date_period_to', models.DateField(blank=True, null=True, verbose_name='Период работы компании по')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.Person')),
            ],
        ),
        migrations.CreateModel(
            name='CompaniesFounderPartners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('first_name', models.CharField(max_length=30, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('middle_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Отчество')),
                ('inn', models.CharField(blank=True, max_length=30, null=True, verbose_name='ИНН')),
                ('company_share', models.IntegerField(blank=True, null=True, verbose_name='Доля в компании')),
                ('person_companies_founder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.PersonCompaniesFounderWOC')),
            ],
        ),
        migrations.CreateModel(
            name='CompaniesCEOFounders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('first_name', models.CharField(max_length=30, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('middle_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Отчество')),
                ('inn', models.CharField(blank=True, max_length=30, null=True, verbose_name='ИНН')),
                ('person_companies_CEO', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.PersonCompaniesCEOWOC')),
            ],
        ),
    ]
