# Generated by Django 3.0.5 on 2020-06-06 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0024_auto_20200606_1219'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companiesceofounders',
            old_name='person_companies_CEO',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='companiesfounderpartners',
            old_name='person_companies_founder',
            new_name='company',
        ),
        migrations.AlterField(
            model_name='ipdetail',
            name='ip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_detail', to='web.PersonIP'),
        ),
    ]
