# Generated by Django 3.0.5 on 2020-06-12 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0026_auto_20200606_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipdetail',
            name='ip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_detail', to='web.PersonIP'),
        ),
    ]
