# Generated by Django 3.0.5 on 2020-06-14 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0027_auto_20200612_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companiesceofounders',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_detail', to='web.PersonCompaniesCEOWOC'),
        ),
        migrations.AlterField(
            model_name='companiesfounderpartners',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_detail', to='web.PersonCompaniesFounderWOC'),
        ),
    ]
