# Generated by Django 3.0.5 on 2020-07-06 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0029_auto_20200614_1910'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonPassport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('passport_date_issued', models.DateField(blank=True, null=True, verbose_name='Дата выдачи паспорта')),
                ('passport_issued', models.CharField(blank=True, max_length=30, null=True, verbose_name='Выдан')),
                ('passport_code', models.CharField(blank=True, max_length=130, null=True, verbose_name='Код паспорта')),
                ('passport_series', models.CharField(blank=True, max_length=130, null=True, verbose_name='Серия паспорта')),
                ('passport_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Номер паспорта')),
                ('passport_birthday_country', models.CharField(blank=True, max_length=150, null=True, verbose_name='Место рождения (страна) ')),
                ('passport_birthday_city', models.CharField(blank=True, max_length=30, null=True, verbose_name='Место рождения (город)')),
                ('passport_address', models.CharField(blank=True, max_length=30, null=True, verbose_name='Ардес регистрации')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Person')),
            ],
        ),
    ]
