# Generated by Django 3.0.5 on 2020-07-06 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0030_personpassport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personpassport',
            name='passport_birthday_country',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Место рождения (страна)'),
        ),
        migrations.AlterField(
            model_name='personpassport',
            name='passport_issued',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Выдан'),
        ),
    ]
