# Generated by Django 3.0.5 on 2020-07-06 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0031_auto_20200706_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personpassport',
            name='passport_address',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Ардес регистрации'),
        ),
        migrations.AlterField(
            model_name='personpassport',
            name='passport_birthday_country',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Место рождения (страна)'),
        ),
        migrations.AlterField(
            model_name='personpassport',
            name='passport_code',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Код паспорта'),
        ),
        migrations.AlterField(
            model_name='personpassport',
            name='passport_issued',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Выдан'),
        ),
        migrations.AlterField(
            model_name='personpassport',
            name='passport_number',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Номер паспорта'),
        ),
        migrations.AlterField(
            model_name='personpassport',
            name='passport_series',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Серия паспорта'),
        ),
    ]
