export const GET_PERSONS = 'GET_PERSONS';
export const GET_PERSON_DETAILS = 'GET_PERSON_DETAILS';
export const DELETE_PERSON_DETAIL = 'DELETE_PERSON_DETAIL';
export const TOGGLE_PERSON_DETAIL= 'TOGGLE_PERSON_DETAIL';
export const OPEN_EDIT_PERSON_DETAIL = 'OPEN_EDIT_PERSON_DETAIL';
export const OPEN_ADD_PERSON_DETAIL = 'OPEN_ADD_PERSON_DETAIL';
export const SAVE_ADD_PERSON_DETAIL = 'SAVE_ADD_PERSON_DETAIL';
export const CLOSE_EDIT_PERSON_DETAIL = 'CLOSE_EDIT_PERSON_DETAIL';
export const UPDATE_PERSON_DETAIL = 'UPDATE_PERSON_DETAIL';



